### ISSUE TITLE
What does RTL mean?

### ISSUE THREAD

**Issue by jskroch** [doobleweb/RTL-Mirror#2]
May I suggest that you spell out the meaning of RTL somewhere in the README.md file?

I figured out that you're talking about text that is written Right To Left, but in my world, RTL also stands for Register Transfer Language (there are [other meanings](https://en.wikipedia.org/wiki/RTL) too.). I thought that your extension might help me with my programming tasks, but it is not relevant to that use.

Thank you,
-jskroch

**Comment by doobleweb** [comment]
Thanks for the input, i'll change it right now.
